### ISSUE TITLE
Copywrite year wrong in ringwormgo-web.andrejbartulin.repl.co

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [ringwormGO-organization/ringwormGO-organization.github.io#1] opened 2022-01-17 13:10 UTC
Title says it all

**Comment by Andrej123456789** [comment] 2022-01-19 07:09
Please, don't be so annyoing. Here at ringwormGO we know the year is wrong and will be fixed. You don't need to comment on every repo, send multiple issues because of one same/similar problem. You sent 5 issues and 4 Pull Request, two were completly wrong in past two days and some contributors agree to all your future issues and Pull Requests on ringwormGO repos will be igored. It is ok to create two or three issue with similar problem, but five with same problem which is caused by not reading documentaion and some existing closed issues. You had Beta14 on your forked repo, and there is no mouse, version Beta15 have mouse. Developers have to programming a lot to give you good product. Year will be changed before or after, but your your ignorance on creating issues and Pull Requests will stay here a lot. We ban you on our Discord server with very good reason, and why you are being put in a situation to be ignore on GitHub because of multiple issues and Pull Requests which some of them was fully wrong in past two days.
This mean that this issue will be closed after this comment and your existing issue in ringOS repo will be open until problem is fixed.
For all future issues and Pull Requests will be closed, ignored and will have `ignored` label until this decision is not withdrawn.
This also valid for repos from @StjepanBM1

Regards,
ringwormGO

**Closed as completed** 2022-01-19 07:13 UTC
Labels: bug

**Comment by ElectroBoy404NotFound** [comment] 2022-01-21 03:56
> Please, don't be so annyoing.

Im not annoying.

> Here at ringwormGO we know the year is wrong and will be fixed. 

Then why was it not fixed?

> You sent 5 issues and 4 Pull Request, two were completly wrong in past two days and some contributors agree to all your future issues and Pull Requests on ringwormGO repos will be igored.

I made 5 issues becuase after making 1, i will find another, etc..

> You had Beta14 on your forked repo, and there is no mouse, version Beta15 have mouse.

The shell script was called "ringos-builder", so i thought that will build the entire thing, but it did'nt. It build Beta-14 when i expected Beta-17.

> Developers have to programming a lot to give you good product.

Yes i know, im also a developer myself

> Year will be changed before or after

It was not changed, i thought that it would be better to create an issue for that.

> We ban you on our Discord server with very good reason

Yes i know

> why you are being put in a situation to be ignore on GitHub because of multiple issues and Pull Requests which some of them was fully wrong in past two days.

I was just trying to help

> For all future issues and Pull Requests will be closed, ignored and will have ignored label until this decision is not withdrawn.

Ahhh yes, another block in 12 hours..

> This also valid for repos from @StjepanBM1

ok

**Comment by Andrej123456789** [comment] 2022-01-21 08:48
ElectroBoy,
you are not anymore ignored. You can send issues and Pull Requests

**Comment by ElectroBoy404NotFound** [comment] 2022-01-21 11:23
> ElectroBoy, you are not anymore ignored. You can send issues and Pull Requests

?? It's been like 2 days?????
